---
- name: check if mongo already installed
  stat: path=/usr/bin/mongo
  register: mongo_bin

- name: MongoDB | Fetch 10Gen signing key
  command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  when: mongo_bin.stat.exists == False

- name: MongoDB | Add 10Gen repository
  shell:
    echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list
    creates=/etc/apt/sources.list.d/mongodb-org-3.0.list
  when: mongo_bin.stat.exists == False

- name: install mongodb
  apt: name=mongodb-org state=latest update_cache=yes
  when: mongo_bin.stat.exists == False

- name: MongoDB - stop server
  service: name=mongod state=stopped
  when: mongo_bin.stat.exists == False

- name: remove data folder
  file: path=/var/lib/mongodb state=absent
  when: mongo_bin.stat.exists == False

- name: copy configuration file
  copy: src=mongod.conf dest=/etc/mongod.conf mode=0644
  when: mongo_bin.stat.exists == False

- name: re-create data folder
  file: path=/var/lib/mongodb state=directory owner=mongodb group=mongodb
  when: mongo_bin.stat.exists == False
